const AUTH_REGISTER = 'AUTH_REGISTER'
const AUTH_LOGIN = 'AUTH_LOGIN'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const LIKE_MESSAGE = 'LIKE_MESSAGE'
const UNLIKE_MESSAGE = 'UNLIKE_MESSAGE'
const CREATE_NEW_MESSAGE = 'CREATE_NEW_MESSAGE'
const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES'
const GET_SPECIFIC_MESSAGE = 'GET_SPECIFIC_MESSAGE'
const DELETE_SPECIFIC_MESSAGE = 'DELETE_SPECIFIC_MESSAGE'
const GET_USER = 'GET_USER'
const UPDATE_USER = 'UPDATE_USER'
const DELETE_USER = 'DELETE_USER'
const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
const CREATE_USER_RESPONSE = 'CREATE_USER_RESPONSE'






